"""init: doc tables + support tables

Revision ID: 2570f8f8f8cc
Revises:
Create Date: 2026-09-27 17:18:34.307319
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2570f8f8f8cc"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_keys",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=False),
        sa.Column("secret_enc", sa.Text(), nullable=False),
        sa.Column("secret_mask", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_test_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_api_keys_provider", "api_keys", ["provider", "enabled"], unique=False)
    op.create_table(
        "checkins",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("items_json", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("json_valid(items_json)", name="ck_checkins_json"),
        sa.PrimaryKeyConstraint("date"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("api_profile_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("type in ('graph','recite')", name="ck_projects_type"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_projects_deleted", "projects", ["deleted_at"], unique=False)
    op.create_table(
        "settings",
        sa.Column("k", sa.String(length=64), nullable=False),
        sa.Column("v", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("k"),
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("project_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_categories_project_sort", "categories", ["project_id", "sort_order"], unique=False
    )
    op.create_table(
        "files",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("project_id", sa.String(length=32), nullable=False),
        sa.Column("server_path", sa.String(length=512), nullable=False),
        sa.Column("orig_name", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("parse_channel", sa.String(length=16), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("parse_channel in ('text','vision')", name="ck_files_channel"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sha256", name="uq_files_sha256"),
    )
    op.create_index("ix_files_deleted", "files", ["deleted_at"], unique=False)
    op.create_index("ix_files_project", "files", ["project_id"], unique=False)
    op.create_table(
        "goals",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("project_id", sa.String(length=32), nullable=False),
        sa.Column("exam_date", sa.Date(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("project_id", sa.String(length=32), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("total_units", sa.Integer(), nullable=False),
        sa.Column("done_units", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("failed_units_json", sa.JSON(), nullable=False),
        sa.Column("checkpoint_json", sa.JSON(), nullable=False),
        sa.Column("tokens_used", sa.Integer(), nullable=False),
        sa.Column("cost_estimate_json", sa.JSON(), nullable=True),
        sa.Column("units_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "status in ('queued','running','success','failed','cancelled')", name="ck_jobs_status"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_jobs_project_created", "jobs", ["project_id", "created_at"], unique=False)
    op.create_index("ix_jobs_status", "jobs", ["status"], unique=False)
    op.create_table(
        "model_profiles",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("text_provider_id", sa.String(length=32), nullable=True),
        sa.Column("text_model", sa.String(length=64), nullable=True),
        sa.Column("vision_provider_id", sa.String(length=32), nullable=True),
        sa.Column("vision_model", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["text_provider_id"], ["api_keys.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["vision_provider_id"], ["api_keys.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pieces",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("project_id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("align_mode", sa.String(length=16), nullable=False),
        sa.Column("recited", sa.Boolean(), nullable=False),
        sa.Column("last_pos", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("align_mode in ('llm','regular')", name="ck_pieces_align_mode"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_pieces_project_sort", "pieces", ["project_id", "sort_order"], unique=False)
    op.create_table(
        "plans",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("project_id", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("target_type", sa.String(length=16), nullable=True),
        sa.Column("target_id", sa.String(length=32), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("status in ('todo','doing','done')", name="ck_plans_status"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_plans_project_due", "plans", ["project_id", "due_date"], unique=False)
    op.create_table(
        "upload_sessions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("project_id", sa.String(length=32), nullable=False),
        sa.Column("orig_name", sa.String(length=255), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("chunk_size", sa.Integer(), nullable=False),
        sa.Column("total_chunks", sa.Integer(), nullable=False),
        sa.Column("received_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_upload_sessions_status", "upload_sessions", ["project_id", "status"], unique=False
    )
    op.create_table(
        "file_parses",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("file_id", sa.String(length=32), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("pages_json", sa.JSON(), nullable=False),
        sa.Column("parser_version", sa.String(length=32), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("tokens_used", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_file_parses_file", "file_parses", ["file_id", "created_at"], unique=False)
    op.create_table(
        "nodes",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("project_id", sa.String(length=32), nullable=False),
        sa.Column("category_id", sa.String(length=32), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("card_summary", sa.Text(), nullable=True),
        sa.Column("user_notes", sa.Text(), nullable=True),
        sa.Column("edited", sa.Boolean(), nullable=False),
        sa.Column("mastery", sa.String(length=8), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("mastery in ('no','mid','yes')", name="ck_nodes_mastery"),
        sa.CheckConstraint("weight between 1 and 3", name="ck_nodes_weight"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_nodes_project_category", "nodes", ["project_id", "category_id"], unique=False
    )
    op.create_table(
        "pairs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("pair_key", sa.String(length=32), nullable=False),
        sa.Column("piece_id", sa.String(length=32), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("zh", sa.Text(), nullable=False),
        sa.Column("en", sa.Text(), nullable=False),
        sa.Column("loc_page", sa.Integer(), nullable=True),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.Column("manually_edited", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["piece_id"], ["pieces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("pair_key", name="uq_pairs_pair_key"),
    )
    op.create_index("ix_pairs_piece_seq", "pairs", ["piece_id", "seq"], unique=False)
    op.create_table(
        "card_quotes",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("node_id", sa.String(length=32), nullable=False),
        sa.Column("quote_text", sa.Text(), nullable=False),
        sa.Column("file_id", sa.String(length=32), nullable=False),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("para", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["files.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_card_quotes_node", "card_quotes", ["node_id"], unique=False)
    op.create_table(
        "edges",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("project_id", sa.String(length=32), nullable=False),
        sa.Column("from_node", sa.String(length=32), nullable=False),
        sa.Column("to_node", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["from_node"], ["nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_node"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("from_node", "to_node", name="uq_edges_pair"),
    )
    op.create_index("ix_edges_project", "edges", ["project_id"], unique=False)
    op.create_table(
        "flashcards",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("node_id", sa.String(length=32), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_flashcards_node", "flashcards", ["node_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_flashcards_node", table_name="flashcards")
    op.drop_table("flashcards")
    op.drop_index("ix_edges_project", table_name="edges")
    op.drop_table("edges")
    op.drop_index("ix_card_quotes_node", table_name="card_quotes")
    op.drop_table("card_quotes")
    op.drop_index("ix_pairs_piece_seq", table_name="pairs")
    op.drop_table("pairs")
    op.drop_index("ix_nodes_project_category", table_name="nodes")
    op.drop_table("nodes")
    op.drop_index("ix_file_parses_file", table_name="file_parses")
    op.drop_table("file_parses")
    op.drop_index("ix_upload_sessions_status", table_name="upload_sessions")
    op.drop_table("upload_sessions")
    op.drop_index("ix_plans_project_due", table_name="plans")
    op.drop_table("plans")
    op.drop_index("ix_pieces_project_sort", table_name="pieces")
    op.drop_table("pieces")
    op.drop_table("model_profiles")
    op.drop_index("ix_jobs_status", table_name="jobs")
    op.drop_index("ix_jobs_project_created", table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("goals")
    op.drop_index("ix_files_project", table_name="files")
    op.drop_index("ix_files_deleted", table_name="files")
    op.drop_table("files")
    op.drop_index("ix_categories_project_sort", table_name="categories")
    op.drop_table("categories")
    op.drop_table("settings")
    op.drop_index("ix_projects_deleted", table_name="projects")
    op.drop_table("projects")
    op.drop_table("checkins")
    op.drop_index("ix_api_keys_provider", table_name="api_keys")
    op.drop_table("api_keys")
    # ### end Alembic commands ###
