export { createApiClient, ApiError } from "./client";
export type { StraytApiClient, StraytApiClientOptions, ApiErrorBody, HttpOptions } from "./client";
export type { components, operations } from "./schemas";

export {
  listProjects,
  createProject,
  renameProject,
  deleteProject,
  getGoal,
  listPieces,
  listPairs,
  putPieceProgress,
  splitPair,
  mergePair,
  getCheckin,
  putCheckin,
  listPlans,
  dailyTodos,
  listApiKeys,
  createApiKey,
  testApiKey,
  deleteApiKey,
  getKv,
  putKv,
  listProviders,
  listFiles,
  uploadFile,
  deleteFile,
  createUploadSession,
  getUploadSession,
  putUploadChunk,
  completeUploadSession,
  abortUploadSession,
  downloadFileRaw,
  listJobs,
  getJob,
  createJob,
  cancelJob,
  resumeJob,
  listProfiles,
  createProfile,
  deleteProfile,
  probeKey,
  fetchBootstrap,
  pushBatch,
  getGraph,
  getGraphDraft,
  confirmGraph,
  getMasteryStats,
  setNodeMastery,
  listCategoryRules,
  putCategoryRules,
  generateFlashcards,
  listFlashcards,
  postFlashcardResult,
  exportSnapshot,
} from "./api";

export type {
  ProjectOut,
  PieceOut,
  PairOut,
  CheckinOut,
  ApiKeyOut,
  ApiKeyProbeIn,
  PlanListOut,
  GoalOut,
  DailyTodos,
  FileOut,
  JobOut,
  JobCreate,
  UploadSessionOut,
  UploadSessionCreate,
  ModelProfileOut,
  ModelProfileIn,
  GraphCategoryOut,
  GraphQuoteOut,
  GraphNodeOut,
  GraphEdgeOut,
  GraphBody,
  GraphDraftNode,
  GraphDraftBody,
  GraphConfirmIn,
  GraphConfirmOut,
  MasteryStatsOut,
  NodeMasteryOut,
  CategoryRuleOut,
  CategoryRuleIn,
  FlashcardOut,
  FlashcardGenOut,
  FlashcardResultOut,
  ListJobsOptions,
  ProviderOut,
} from "./api";