/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/checkins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 打卡（同日覆盖） */
        put: operations["put_checkin_api_v1_checkins_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checkins/{day}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查某天打卡 */
        get: operations["get_checkin_api_v1_checkins__day__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/export/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全部项目数据一键导出 JSON 快照 */
        get: operations["export_snapshot_api_v1_export_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 项目资料列表 */
        get: operations["list_files_api_v1_files_get"];
        put?: never;
        /** 直传上传（≤50MB） */
        post: operations["upload_direct_api_v1_files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{file_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 软删文件（实体移入回收站） */
        delete: operations["delete_file_api_v1_files__file_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{file_id}/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 下载原始文件（出处回看二期用） */
        get: operations["download_raw_api_v1_files__file_id__raw_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/flashcards/{flashcard_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 自测结果回写
         * @description 答对/答错推进一档掌握度（no↔mid↔yes），两端钳位。
         */
        post: operations["post_flashcard_result_api_v1_flashcards__flashcard_id__result_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务列表 */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        /**
         * 新建加工任务并开跑
         * @description 入队并立即在服务端后台开跑，客户端可以关窗。
         *
         *     任务表里同时写 ``file_id``，断点续跑靠它找回要加工的文件。
         *     图谱任务在创建时就校验 LLM 配置：没有模型就没有知识点，与其建一个
         *     必然会失败的活，不如一开始就拦住并说明原因。
         */
        post: operations["create_job_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务详情（含逐章进度与断点） */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 取消排队中、运行中或已中断的任务 */
        post: operations["cancel_job_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/graph-confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 预览确认并入库
         * @description 把草稿（带手动调整）一次性原子落库，覆盖项目旧图谱。
         */
        post: operations["confirm_graph_api_v1_jobs__job_id__graph_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/graph-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 阅读取预览草稿
         * @description 抽取任务完成后的预览草稿（尚未落正式表）。
         */
        get: operations["get_graph_draft_api_v1_jobs__job_id__graph_draft_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 断点续跑失败或已中断的任务 */
        post: operations["resume_job_api_v1_jobs__job_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{node_id}/mastery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 设置节点掌握度
         * @description 直接写掌握度（在线路径）。离线走弱同步 ``node_mastery`` 实体。
         */
        put: operations["put_node_mastery_api_v1_nodes__node_id__mastery_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 阶段计划列表 */
        get: operations["list_plans_api_v1_plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 每日待办聚合 */
        get: operations["daily_todos_api_v1_plans_daily_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 项目列表 */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** 新建项目 */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 项目详情 */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        /** 软删进回收站 */
        delete: operations["delete_project_api_v1_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** 改名（类型不可改） */
        patch: operations["rename_project_api_v1_projects__project_id__patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/flashcards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 闪卡卡组
         * @description 按项目取卡组，可只取某掌握度（自测优先复习弱项）。
         */
        get: operations["list_flashcards_api_v1_projects__project_id__flashcards_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/flashcards/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 按当前图谱重建闪卡（幂等）
         * @description 从已确认节点确定性重建整副卡组：question=名称，answer=概要/摘录。
         *
         *     不调 LLM —— 概要/摘录在抽取时已限"仅基于给定材料"，这里复用它。
         *     同一事务先清旧卡再全量插入（与图谱擦除重建同语义）。
         */
        post: operations["generate_flashcards_api_v1_projects__project_id__flashcards_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/goal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 考试目标 */
        get: operations["get_goal_api_v1_projects__project_id__goal_get"];
        /** 设置考试目标 */
        put: operations["put_goal_api_v1_projects__project_id__goal_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 图谱全量拉取
         * @description 确认入库后的完整图谱：分类 → 节点（带引文）→ 关联。
         */
        get: operations["get_graph_api_v1_projects__project_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/mastery-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 掌握度统计
         * @description 按掌握度三级与一级分类做聚合，供图谱视图着色与进度概览。
         */
        get: operations["get_mastery_stats_api_v1_projects__project_id__mastery_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/pieces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 篇目列表 */
        get: operations["list_pieces_api_v1_projects__project_id__pieces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/pieces/{piece_id}/pairs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取段落对（背诵舱数据源） */
        get: operations["list_pairs_api_v1_projects__project_id__pieces__piece_id__pairs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/pieces/{piece_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 上报背诵进度 */
        put: operations["put_progress_api_v1_projects__project_id__pieces__piece_id__progress_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 从回收站恢复 */
        post: operations["restore_project_api_v1_projects__project_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Key 列表（只含掩码） */
        get: operations["list_keys_api_v1_settings_api_keys_get"];
        put?: never;
        /** 添加 Key */
        post: operations["create_key_api_v1_settings_api_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/api-keys/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 试连（不落库，≤10s） */
        post: operations["probe_key_api_v1_settings_api_keys_probe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/api-keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除 Key */
        delete: operations["delete_key_api_v1_settings_api_keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/api-keys/{key_id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 连通性测试（≤10s，F6）
         * @description F6 硬要求：10s 内返回成功/失败 + 原因（Key 错误 / 网络不通 / 额度不足）。
         */
        post: operations["test_key_api_v1_settings_api_keys__key_id__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/kv/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读 KV */
        get: operations["get_kv_api_v1_settings_kv__key__get"];
        /** 写 KV */
        put: operations["put_kv_api_v1_settings_kv__key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/model-profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 模型档案列表 */
        get: operations["list_profiles_api_v1_settings_model_profiles_get"];
        put?: never;
        /** 新建档案 */
        post: operations["create_profile_api_v1_settings_model_profiles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/model-profiles/{profile_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除档案 */
        delete: operations["delete_profile_api_v1_settings_model_profiles__profile_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 已接入的服务商与模型（给设置页下拉框） */
        get: operations["list_providers_api_v1_settings_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重放写队列 */
        post: operations["push_batch_api_v1_sync_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全量快照（打开应用时一次） */
        get: operations["bootstrap_api_v1_sync_bootstrap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upload-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 声明分块上传会话 */
        post: operations["create_session_api_v1_upload_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upload-sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询已收分块（续传依据） */
        get: operations["get_session_api_v1_upload_sessions__session_id__get"];
        put?: never;
        post?: never;
        /** 放弃会话并清理分片 */
        delete: operations["abort_session_api_v1_upload_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upload-sessions/{session_id}/chunks/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 上传单个分块（可重复调用，幂等覆盖） */
        put: operations["put_chunk_api_v1_upload_sessions__session_id__chunks__index__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upload-sessions/{session_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 合并分块并校验 SHA-256 */
        post: operations["complete_session_api_v1_upload_sessions__session_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 存活探针（免鉴权） */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiKeyIn */
        ApiKeyIn: {
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Provider
             * @enum {string}
             */
            provider: "openai" | "deepseek" | "moonshot" | "qwen" | "doubao" | "glm" | "openai_compatible";
            /** Secret */
            secret: string;
        };
        /** ApiKeyOut */
        ApiKeyOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Enabled */
            enabled: boolean;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Last Test Json */
            last_test_json?: {
                [key: string]: unknown;
            } | null;
            /** Provider */
            provider: string;
            /** Secret Mask */
            secret_mask: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ApiKeyProbeIn
         * @description 不落库的试连：用户刚粘贴 Key 时先试，避免存一堆废 Key。
         */
        ApiKeyProbeIn: {
            /** Model */
            model?: string | null;
            /**
             * Provider
             * @enum {string}
             */
            provider: "openai" | "deepseek" | "moonshot" | "qwen" | "doubao" | "glm" | "openai_compatible";
            /** Secret */
            secret: string;
        };
        /** BatchIn */
        BatchIn: {
            /** Ops */
            ops: components["schemas"]["OpIn"][];
        };
        /** BatchOut */
        BatchOut: {
            /** Results */
            results: components["schemas"]["OpResult"][];
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
        };
        /** Body_upload_direct_api_v1_files_post */
        Body_upload_direct_api_v1_files_post: {
            /** File */
            file: string;
        };
        /** CategoryMasteryOut */
        CategoryMasteryOut: {
            /** Category Id */
            category_id: string | null;
            /** Mid */
            mid: number;
            /** Name */
            name: string;
            /** No */
            no: number;
            /** Total */
            total: number;
            /** Yes */
            yes: number;
        };
        /** CheckinIn */
        CheckinIn: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Items */
            items?: string[];
        };
        /** CheckinOut */
        CheckinOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Items Json */
            items_json: string[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** FileOut */
        FileOut: {
            /** Deleted At */
            deleted_at?: string | null;
            /** Id */
            id: string;
            /** Orig Name */
            orig_name: string;
            /** Page Count */
            page_count?: number | null;
            /**
             * Parse Channel
             * @enum {string}
             */
            parse_channel: "text" | "vision";
            /** Project Id */
            project_id: string;
            /** Sha256 */
            sha256: string;
            /** Size */
            size: number;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /** FlashcardGenOut */
        FlashcardGenOut: {
            /** Created */
            created: number;
            /** Ok */
            ok: boolean;
            /** Skipped */
            skipped: number;
        };
        /** FlashcardOut */
        FlashcardOut: {
            /** Answer */
            answer: string;
            /** Category Id */
            category_id: string | null;
            /** Id */
            id: string;
            /** Mastery */
            mastery: string;
            /** Node Id */
            node_id: string;
            /** Page */
            page: number | null;
            /** Question */
            question: string;
        };
        /** FlashcardResultIn */
        FlashcardResultIn: {
            /** Correct */
            correct: boolean;
        };
        /** FlashcardResultOut */
        FlashcardResultOut: {
            /** Flashcard Id */
            flashcard_id: string;
            /** Node Id */
            node_id: string;
            /** Node Mastery */
            node_mastery: string;
        };
        /** GoalIn */
        GoalIn: {
            /**
             * Exam Date
             * Format: date
             */
            exam_date: string;
        };
        /** GoalOut */
        GoalOut: {
            /**
             * Exam Date
             * Format: date
             */
            exam_date: string;
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * GraphConfirmIn
         * @description 预览确认时的三种调整：删误抽 / 调分类 / 改内容。
         */
        GraphConfirmIn: {
            /** Delete Keys */
            delete_keys?: string[];
            /** Edits */
            edits?: {
                [key: string]: components["schemas"]["NodeEdit"];
            };
            /** Reassign */
            reassign?: {
                [key: string]: string;
            };
        };
        /** GraphConfirmOut */
        GraphConfirmOut: {
            /** Category Count */
            category_count: number;
            /** Edge Count */
            edge_count: number;
            /** Edited Nodes */
            edited_nodes: number;
            /** Node Count */
            node_count: number;
            /** Ok */
            ok: boolean;
            /** Reason */
            reason: string;
            /** Warnings */
            warnings?: string[];
        };
        /** GraphDraftOut */
        GraphDraftOut: {
            /** Draft */
            draft: {
                [key: string]: unknown;
            };
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobCreate
         * @description 新建加工任务。``recite_align`` 背诵对齐；``graph_extract`` 图谱抽取。
         */
        JobCreate: {
            /** File Id */
            file_id: string;
            /**
             * Overwrite
             * @default false
             */
            overwrite: boolean;
            /** Project Id */
            project_id: string;
            /**
             * Type
             * @default recite_align
             * @enum {string}
             */
            type: "recite_align" | "graph_extract";
        };
        /** JobOut */
        JobOut: {
            /** Checkpoint Json */
            checkpoint_json: {
                [key: string]: unknown;
            };
            /** Cost Estimate Json */
            cost_estimate_json?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Done Units */
            done_units: number;
            /** Error */
            error?: string | null;
            /** Failed Units Json */
            failed_units_json: unknown[];
            /**
             * Heartbeat At
             * Format: date-time
             */
            heartbeat_at: string;
            /** Id */
            id: string;
            /** Progress */
            progress: number;
            /** Project Id */
            project_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "success" | "failed" | "cancelled" | "interrupted";
            /** Tokens Used */
            tokens_used: number;
            /** Total Units */
            total_units: number;
            /** Type */
            type: string;
            /** Units Json */
            units_json: unknown[];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** KvIn */
        KvIn: {
            /** Value */
            value: string;
        };
        /** MasteryIn */
        MasteryIn: {
            /**
             * Mastery
             * @enum {string}
             */
            mastery: "no" | "mid" | "yes";
        };
        /** MasteryStatsOut */
        MasteryStatsOut: {
            /** By Category */
            by_category: components["schemas"]["CategoryMasteryOut"][];
            /** By Mastery */
            by_mastery: {
                [key: string]: number;
            };
            /** Mastery Ratio */
            mastery_ratio: number;
            /** Project Id */
            project_id: string;
            /** Total */
            total: number;
        };
        /** ModelProfileIn */
        ModelProfileIn: {
            /** Name */
            name: string;
            /** Text Key Id */
            text_key_id?: string | null;
            /** Text Model */
            text_model?: string | null;
            /** Vision Key Id */
            vision_key_id?: string | null;
            /** Vision Model */
            vision_model?: string | null;
        };
        /** ModelProfileOut */
        ModelProfileOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Text Model */
            text_model: string | null;
            /** Text Provider Id */
            text_provider_id: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Vision Model */
            vision_model: string | null;
            /** Vision Provider Id */
            vision_provider_id: string | null;
        };
        /**
         * NodeEdit
         * @description 预览确认时对一个节点的有限手动编辑（F14）。
         */
        NodeEdit: {
            /** Name */
            name?: string | null;
            /** Summary */
            summary?: string | null;
        };
        /** NodeMasteryOut */
        NodeMasteryOut: {
            /** Id */
            id: string;
            /** Mastery */
            mastery: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * OpIn
         * @description 一条写队列操作。
         */
        OpIn: {
            /**
             * Client Ts
             * Format: date-time
             * @description 客户端写入时刻（UTC naive）
             */
            client_ts: string;
            /**
             * Entity
             * @description 可写实体：piece_progress, pair_edit, checkin, plan, goal, node_mastery
             */
            entity: string;
            /** Entity Id */
            entity_id: string;
            /**
             * Op Id
             * @description 幂等键，客户端生成
             */
            op_id: string;
            /** Patch */
            patch?: {
                [key: string]: unknown;
            };
        };
        /** OpResult */
        OpResult: {
            /** Op Id */
            op_id: string;
            /** Reason */
            reason?: string | null;
            /** Server Updated At */
            server_updated_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "applied" | "skipped" | "conflict" | "error";
        };
        /** PairOut */
        PairOut: {
            /** En */
            en: string;
            /** Loc Page */
            loc_page?: number | null;
            /** Manually Edited */
            manually_edited: boolean;
            /** Needs Review */
            needs_review: boolean;
            /** Pair Key */
            pair_key: string;
            /** Seq */
            seq: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Zh */
            zh: string;
        };
        /** PieceOut */
        PieceOut: {
            /**
             * Align Mode
             * @enum {string}
             */
            align_mode: "llm" | "regular";
            /** Id */
            id: string;
            /** Last Pos */
            last_pos: number;
            /**
             * Pair Count
             * @default 0
             */
            pair_count: number;
            /** Project Id */
            project_id: string;
            /** Recited */
            recited: boolean;
            /** Sort Order */
            sort_order: number;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PieceProgressIn
         * @description 背诵舱进度。客户端可离线写，联网后随写队列上传。
         */
        PieceProgressIn: {
            /**
             * Client Ts
             * Format: date-time
             */
            client_ts: string;
            /** Last Pos */
            last_pos: number;
            /** Recited */
            recited?: boolean | null;
        };
        /**
         * PlanListOut
         * @description 阶段计划列表项：在 PlanOut 上附加相对参考日的派生字段。
         */
        PlanListOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Days Until */
            days_until?: number | null;
            /** Due Date */
            due_date: string | null;
            /** Id */
            id: string;
            /**
             * Overdue
             * @default false
             */
            overdue: boolean;
            /** Project Id */
            project_id: string;
            /** Sort Order */
            sort_order: number;
            /**
             * Status
             * @enum {string}
             */
            status: "todo" | "doing" | "done";
            /** Target Id */
            target_id: string | null;
            /** Target Type */
            target_type: string | null;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Api Profile Id */
            api_profile_id?: string | null;
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "graph" | "recite";
        };
        /** ProjectOut */
        ProjectOut: {
            /** Api Profile Json */
            api_profile_json?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at?: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Type
             * @enum {string}
             */
            type: "graph" | "recite";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * UploadSessionCreate
         * @description 客户端先声明文件指纹，服务端据此判断走直传还是分块。
         */
        UploadSessionCreate: {
            /** Orig Name */
            orig_name: string;
            /** Sha256 */
            sha256: string;
            /** Size */
            size: number;
        };
        /** UploadSessionOut */
        UploadSessionOut: {
            /** Chunk Size */
            chunk_size: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Orig Name */
            orig_name: string;
            /** Project Id */
            project_id: string;
            /** Received Json */
            received_json: {
                [key: string]: unknown;
            };
            /** Sha256 */
            sha256: string;
            /** Size */
            size: number;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "complete" | "aborted";
            /** Total Chunks */
            total_chunks: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    put_checkin_api_v1_checkins_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckinIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckinOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_checkin_api_v1_checkins__day__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                day: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckinOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_snapshot_api_v1_export_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_files_api_v1_files_get: {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_direct_api_v1_files_post: {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_direct_api_v1_files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_file_api_v1_files__file_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_raw_api_v1_files__file_id__raw_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_flashcard_result_api_v1_flashcards__flashcard_id__result_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                flashcard_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FlashcardResultIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlashcardResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                status?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_graph_api_v1_jobs__job_id__graph_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphConfirmIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphConfirmOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_draft_api_v1_jobs__job_id__graph_draft_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphDraftOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_job_api_v1_jobs__job_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_node_mastery_api_v1_nodes__node_id__mastery_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                node_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MasteryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeMasteryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plans_api_v1_plans_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                status?: string | null;
                /** @description 排序参考日（used for 逾期判定），默认今天 */
                ref_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanListOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    daily_todos_api_v1_plans_daily_get: {
        parameters: {
            query?: {
                /** @description 待办日，默认今天 */
                day?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: {
                /** @description 回收站视图：只列已删项目 */
                include_deleted?: boolean;
                type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_v1_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_project_api_v1_projects__project_id__patch: {
        parameters: {
            query: {
                name: string;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_flashcards_api_v1_projects__project_id__flashcards_get: {
        parameters: {
            query?: {
                mastery?: ("no" | "mid" | "yes") | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlashcardOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_flashcards_api_v1_projects__project_id__flashcards_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlashcardGenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_goal_api_v1_projects__project_id__goal_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_goal_api_v1_projects__project_id__goal_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_api_v1_projects__project_id__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mastery_stats_api_v1_projects__project_id__mastery_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MasteryStatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pieces_api_v1_projects__project_id__pieces_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PieceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pairs_api_v1_projects__project_id__pieces__piece_id__pairs_get: {
        parameters: {
            query?: {
                /** @description 续传起点 */
                from_seq?: number;
                limit?: number;
            };
            header?: never;
            path: {
                project_id: string;
                piece_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_progress_api_v1_projects__project_id__pieces__piece_id__progress_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                piece_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PieceProgressIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PieceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_project_api_v1_projects__project_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_keys_api_v1_settings_api_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyOut"][];
                };
            };
        };
    };
    create_key_api_v1_settings_api_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    probe_key_api_v1_settings_api_keys_probe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiKeyProbeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_key_api_v1_settings_api_keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_key_api_v1_settings_api_keys__key_id__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_kv_api_v1_settings_kv__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_kv_api_v1_settings_kv__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KvIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_profiles_api_v1_settings_model_profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelProfileOut"][];
                };
            };
        };
    };
    create_profile_api_v1_settings_model_profiles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_profile_api_v1_settings_model_profiles__profile_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                profile_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_providers_api_v1_settings_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    push_batch_api_v1_sync_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bootstrap_api_v1_sync_bootstrap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    create_session_api_v1_upload_sessions_post: {
        parameters: {
            query: {
                project_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadSessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_v1_upload_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    abort_session_api_v1_upload_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_chunk_api_v1_upload_sessions__session_id__chunks__index__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_session_api_v1_upload_sessions__session_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
